config/routes.rb
Rails.application.routes.draw do
	if Rails.env.development?
		resources :project_skills
		resources :project_images
		resources :skills
		resources :projects
		get 'about' => 'home#about', as: :about
		get 'browse' => 'projects#browse', as: :browse
	else
		get 'about' => 'home#about', as: :about
		get 'projects/:id' => 'projects#show', as: :project
		get 'projects' => 'projects#browse', as: :browse
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	

	root :to => 'home#home'
end

app/models/project.rb
class Project < ApplicationRecord
	# Relationships
	has_many :project_images
	has_many :project_skills
	has_many :skills, through: :project_skills

	# Scopes
	scope :chronological, -> { nil } # TODO projects ordered by :created_at
	scope :for_user, -> { nil } # TODO projects for a given user
	scope :for_skill, ->(skill_name) { nil } # TODO projects for a given skill name
	scope :featured, -> { where(:order < 0) }
	scope :unfeatured, -> { where(:order >= 0) }
	scope :ordered, -> { order(order: :asc, title: :asc) } # TODO projects ordered by :order

	# Validations
	validates :title, presence: true
	# TODO uniqueness of :order per project id validation
	# TODO cover url regex validation

	def to_param
		self.title.gsub(' ','-')
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.ordered
  end

  def browse
    @projects = Project.all.ordered
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project_skills = @project.project_skills.ordered
    @project_images = @project.project_images.ordered
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by(title: params[:id].gsub('-', ' '))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :subtitle, :snippet, :description, :dates, :collaboration, :cover_url, :order, :visibility, :site_link, :github_link)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :project_subtitle %>
  </div>

  <div class="field">
    <%= form.label :snippet %>
    <%= form.text_area :snippet, id: :project_snippet, rows: 10, cols: 50 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description, rows: 15, cols: 50 %>
  </div>

  <div class="field">
    <%= form.label :dates %>
    <%= form.text_field :dates, id: :project_dates %>
  </div>

  <div class="field">
    <%= form.label :collaboration %>
    <%= form.text_field :collaboration, id: :project_collaboration %>
  </div>

  <div class="field">
    <%= form.label :cover_url %>
    <%= form.text_field :cover_url, id: :project_cover_url %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order, id: :project_order %>
  </div>

  <div class="field">
    <%= form.label :visibility %>
    <%= form.text_field :visibility, id: :project_visibility %>
  </div>

  <div class="field">
    <%= form.label :site_link %>
    <%= form.text_field :site_link, id: :project_site_link %>
  </div>

  <div class="field">
    <%= form.label :github_link %>
    <%= form.text_field :github_link, id: :project_github_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project_card.html.erb
<div class="project-card">
	<div class="project-contents">
		<div class="project-cover">
			<%= link_to(project_path(@project), class: "cover-link") do %><% end %>
			<div class="cover-image" style="background-image: url(<%= discover_image(@project.cover_url) %>);">
			</div>
			<div class="cover-overlay"><%= raw @project.snippet %></div>
		</div>
		<div class="project-meta">
			<%= link_to(project_path(@project)) do %>
			<div class="meta-left">
				<h3 class="meta-title">
					<%= @project.title %>
				</h3>
				<h5 class="meta-subtitle">
					<%= @project.subtitle %>
				</h5>
			</div>
			<% end %>
			<div class="meta-right">
				<div class="meta-skills">
					<% meta_skills = @project.project_skills.ordered.meta.take(3) %>
					<% for project_skill in meta_skills %>
						<% skill = project_skill.skill %>
						<div class="meta-skill meta-skill-1-<%= meta_skills.size %>">
							<div class="skill-image" style="background-image: url(<%= discover_image(skill.img_url) %>)"></div>
							<div class="skill-label"><%= skill.name %></div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/projects/browse.html.erb
<div class="project-list">
    <% for @project in @projects %>
    	<div class="project-block" id="<%= @project.title.gsub(' ', '-') %>">
	        <%= render 'project_card' %>
	    </div>
    <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
<!--       <th>Snippet</th>
      <th>Description</th> -->
      <th>Dates</th>
      <th>Collaboration</th>
      <th>Cover url</th>
      <th>Order</th>
      <th>Visibility</th>
      <th>Site link</th>
      <th>Github link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.subtitle %></td>
<!--         <td><%= project.snippet %></td>
        <td><%= project.description %></td> -->
        <td><%= project.dates %></td>
        <td><%= project.collaboration %></td>
        <td><%= project.cover_url %></td>
        <td><%= project.order %></td>
        <td><%= project.visibility %></td>
        <td><%= project.site_link %></td>
        <td><%= project.github_link %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="large-container" style="margin-bottom: 20px;">
	<h1 class="project-title"><%= @project.title %></h1>
	<h4 class="project-subtitle"><%= @project.subtitle %></h4>
	<div class="project-preface">
		<div class="project-slides" style="background-image: url(<%= discover_image(@project.cover_url) %>);">
			<iframe src="" frameborder="0" allowfullscreen></iframe>
			<div class="project-slides-background"></div>
		</div>
		<div class="project-details">
			<div class="details-main">
				<div class="details-brand" style="background-image: url(<%= discover_image(@project.cover_url) %>);"></div>
				<div class="details-snippet-and-skills">
					<div class="details-snippet"><%= raw @project.description %></div>
				</div>
			</div>
		</div>
	</div>
	<div class="project-postface">
		<div class="project-description">
			<div class="slide-block" onclick="switchSlides(this, '<%= discover_slide(@project.cover_url) %>');">
			<div class="slide-preview">
					<div class="slide-preview-image" style="background-image: url(<%= discover_image(@project.cover_url) %>);"></div>
				</div>
			</div>
			<% for project_image in @project_images %>
				<div class="slide-block" onclick="switchSlides(this, '<%= discover_slide(project_image.img_url) %>');">
					<div class="slide-preview">
						<div class="slide-preview-image" style="background-image: url(<%= discover_image(project_image.img_url) %>);"></div>
						<!-- If youtube video, add white play button -->
						<% if /img\.youtube\.com/.match(project_image.img_url) %>
							<div class="slide-preview-play" style="background-image: url(<%= discover_image('icons/play_button_white.png') %>);"></div>
						<% end %>
					</div>
				</div>
			<% end %>
			<script>
				$('.slide-block').first().click();
			</script>
		</div>
		<div class="project-sidebar">
			<div class="sidebar-details details-skills">
				<h4>Skills</h4>
				<% for project_skill in @project_skills %>
					<% skill = project_skill.skill %>
					<a class="details-skill" href="<%= skill.dev_link %>" target="_blank">
						<div class="skill-image" style="background-image: url(<%= discover_image(skill.img_url) %>)"></div>
						<div class="skill-label"><%= skill.name %></div>
					</a>
				<% end %>
			</div>
			<div class="sidebar-details details-misc">
				<!-- GitHub Link -->
				<% if @project.github_link != "" %>
					<h4>Github Link</h4>
					<a href="<%= @project.github_link %>" target="_blank">
						<div class="icon icon-12x12" style="background-image: url(<%= discover_image("icons/external_link_white.png") %>);"></div>
						<%= clean_url(@project.github_link) %>
					</a>
				<% end %>
				<!-- Project Link -->
				<% if @project.site_link != "" %>
					<h4>Project Link</h4>
					<a href="<%= @project.site_link %>" target="_blank">
						<div class="icon icon-12x12" style="background-image: url(<%= discover_image("icons/external_link_white.png") %>);"></div>
						<%= clean_url(@project.site_link) %>
					</a>
				<% end %>
				<!-- Project Dates -->
				<% if @project.dates != "" %>
					<h4>Project Dates</h4>
					<%= @project.dates %>
				<% end %>
			</div>
		</div>
	</div>
	<% if @project_images.length > 1 %>
		<div class="mobile-show visit-desktop">
			Visit on desktop to see this project's screenshots!
		</div>
	<% end %>
	<% if false %>
		<p id="notice"><%= notice %></p>
		<%= link_to 'Edit', edit_project_path(@project) %> |
	<% end %>
	<%= link_to browse_path(anchor: "#{@project.title.gsub(' ', '-')}"), class: 'project-back-link' do %>
		Back to Projects
	<% end %>
</div>