config/routes.rb
Rails.application.routes.draw do
	if Rails.env.development?
		resources :project_skills
		resources :project_images
		resources :skills
		resources :projects
		get 'about' => 'home#about', as: :about
		get 'browse' => 'projects#browse', as: :browse
	else
		get 'about' => 'home#about', as: :about
		get 'projects/:id' => 'projects#show', as: :project
		get 'projects' => 'projects#browse', as: :browse
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	

	root :to => 'home#home'
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
	# Relationships
	belongs_to :project
	belongs_to :skill

	# Scope
	scope :for_skill, ->(skill_id) { nil } # TODO project skills of given skill name
	scope :order_by_project, -> { joins(:project).order('projects.title ASC') }
	scope :ordered, -> { order(order: :asc) }
	scope :meta, -> { where(meta: true) }

	# Validations
	validates_numericality_of :order, only_integer: true, greater_than_or_equal_to: 0
	# TODO uniqueness of :order per project id validation
end

app/controllers/project_skills_controller.rb
class ProjectSkillsController < ApplicationController
  before_action :set_project_skill, only: [:show, :edit, :update, :destroy]

  # GET /project_skills
  # GET /project_skills.json
  def index
    @project_skills = ProjectSkill.order_by_project.ordered
  end

  # GET /project_skills/1
  # GET /project_skills/1.json
  def show
  end

  # GET /project_skills/new
  def new
    @project_skill = ProjectSkill.new
  end

  # GET /project_skills/1/edit
  def edit
  end

  # POST /project_skills
  # POST /project_skills.json
  def create
    @project_skill = ProjectSkill.new(project_skill_params)

    respond_to do |format|
      if @project_skill.save
        format.html { redirect_to project_skills_path, notice: 'Project skill was successfully created.' }
        format.json { render :show, status: :created, location: @project_skill }
      else
        format.html { render :new }
        format.json { render json: @project_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_skills/1
  # PATCH/PUT /project_skills/1.json
  def update
    respond_to do |format|
      if @project_skill.update(project_skill_params)
        format.html { redirect_to project_skills_path, notice: 'Project skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_skill }
      else
        format.html { render :edit }
        format.json { render json: @project_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_skills/1
  # DELETE /project_skills/1.json
  def destroy
    @project_skill.destroy
    respond_to do |format|
      format.html { redirect_to project_skills_url, notice: 'Project skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_skill
      @project_skill = ProjectSkill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_skill_params
      params.require(:project_skill).permit(:project_id, :skill_id, :description, :order, :meta)
    end
end

app/helpers/project_skills_helper.rb
module ProjectSkillsHelper
end

app/views/project_skills/_form.html.erb
<%= form_with(model: project_skill, local: true) do |form| %>
  <% if project_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_skill.errors.count, "error") %> prohibited this project_skill from being saved:</h2>

      <ul>
      <% project_skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.collection_select :project_id, Project.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :skill_id %>
    <%= form.collection_select :skill_id, Skill.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_skill_description %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order, id: :project_skill_order %>
  </div>

  <div class="field">
    <%= form.label :meta %>
    <%= form.check_box :meta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_skills/edit.html.erb
<h1>Editing Project Skill</h1>

<%= render 'form', project_skill: @project_skill %>

<%= link_to 'Show', @project_skill %> |
<%= link_to 'Back', project_skills_path %>

app/views/project_skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Skills</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th></th>
      <th>Skill</th>
      <th>Description</th>
      <th>Order</th>
      <th>Meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_skills.each do |project_skill| %>
      <tr>
        <td><%= Project.find_by_id(project_skill.project_id).title %></td>
        <td><div class="icon icon-20x20" style="background-image: url(<%= discover_image(project_skill.skill.img_url) %>);"></div></td>
        <td><%= Skill.find_by_id(project_skill.skill_id).name %></td>
        <td><%= project_skill.description %></td>
        <td><%= project_skill.order %></td>
        <td><%= project_skill.meta %></td>
        <td><%= link_to 'Show', project_skill %></td>
        <td><%= link_to 'Edit', edit_project_skill_path(project_skill) %></td>
        <td><%= link_to 'Destroy', project_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Skill', new_project_skill_path %>

app/views/project_skills/new.html.erb
<h1>New Project Skill</h1>

<%= render 'form', project_skill: @project_skill %>

<%= link_to 'Back', project_skills_path %>

app/views/project_skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_skill.project_id %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @project_skill.skill_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project_skill.description %>
</p>

<p>
  <strong>Order:</strong>
  <%= @project_skill.order %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @project_skill.meta %>
</p>

<%= link_to 'Edit', edit_project_skill_path(@project_skill) %> |
<%= link_to 'Back', project_skills_path %>