config/routes.rb
Rails.application.routes.draw do
	if Rails.env.development?
		resources :project_skills
		resources :project_images
		resources :skills
		resources :projects
		get 'about' => 'home#about', as: :about
		get 'browse' => 'projects#browse', as: :browse
	else
		get 'about' => 'home#about', as: :about
		get 'projects/:id' => 'projects#show', as: :project
		get 'projects' => 'projects#browse', as: :browse
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	

	root :to => 'home#home'
end

app/models/project_image.rb
class ProjectImage < ApplicationRecord
	# Relationships
	belongs_to :project

	# Scopes
	scope :for_project, ->(project_id) { where(id: project_id) } # TODO skills for a project id
	scope :order_by_project, -> { joins(:project).order('projects.title ASC') }
	scope :ordered, -> { order(order: :asc) } # TODO projects ordered by :order

	# Validations
	validates_numericality_of :order, only_integer: true, greater_than_or_equal_to: 0
	# TODO uniqueness of :order per project id validation
	# TODO image url regex validation
end

app/controllers/project_images_controller.rb
class ProjectImagesController < ApplicationController
  before_action :set_project_image, only: [:show, :edit, :update, :destroy]

  # GET /project_images
  # GET /project_images.json
  def index
    @project_images = ProjectImage.order_by_project
  end

  # GET /project_images/1
  # GET /project_images/1.json
  def show
  end

  # GET /project_images/new
  def new
    @project_image = ProjectImage.new
  end

  # GET /project_images/1/edit
  def edit
  end

  # POST /project_images
  # POST /project_images.json
  def create
    @project_image = ProjectImage.new(project_image_params)

    respond_to do |format|
      if @project_image.save
        format.html { redirect_to project_images_path, notice: 'Project image was successfully created.' }
        format.json { render :show, status: :created, location: @project_image }
      else
        format.html { render :new }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_images/1
  # PATCH/PUT /project_images/1.json
  def update
    respond_to do |format|
      if @project_image.update(project_image_params)
        format.html { redirect_to @project_image, notice: 'Project image was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_image }
      else
        format.html { render :edit }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_images/1
  # DELETE /project_images/1.json
  def destroy
    @project_image.destroy
    respond_to do |format|
      format.html { redirect_to project_images_url, notice: 'Project image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_image
      @project_image = ProjectImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_image_params
      params.require(:project_image).permit(:project_id, :caption, :img_url, :order)
    end
end

app/helpers/project_images_helper.rb
module ProjectImagesHelper
end

app/views/project_images/_form.html.erb
<%= form_with(model: project_image, local: true) do |form| %>
  <% if project_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_image.errors.count, "error") %> prohibited this project_image from being saved:</h2>

      <ul>
      <% project_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.collection_select :project_id, Project.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption, id: :project_image_caption %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :project_image_img_url %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order, id: :project_image_order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_images/edit.html.erb
<h1>Editing Project Image</h1>

<%= render 'form', project_image: @project_image %>

<%= link_to 'Show', @project_image %> |
<%= link_to 'Back', project_images_path %>

app/views/project_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Images</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Caption</th>
      <th>Img url</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_images.each do |project_image| %>
      <tr>
        <td><%= project_image.project.title %></td>
        <td><%= project_image.caption %></td>
        <td><%= project_image.img_url %></td>
        <td><%= project_image.order %></td>
        <td><%= link_to 'Show', project_image %></td>
        <td><%= link_to 'Edit', edit_project_image_path(project_image) %></td>
        <td><%= link_to 'Destroy', project_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Image', new_project_image_path %>

app/views/project_images/new.html.erb
<h1>New Project Image</h1>

<%= render 'form', project_image: @project_image %>

<%= link_to 'Back', project_images_path %>

app/views/project_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_image.project_id %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @project_image.caption %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @project_image.img_url %>
</p>

<p>
  <strong>Order:</strong>
  <%= @project_image.order %>
</p>

<%= link_to 'Edit', edit_project_image_path(@project_image) %> |
<%= link_to 'Back', project_images_path %>